nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 12h
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi

grafana:
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.monitoring.svc:9090
        access: proxy
        isDefault: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - prometheus
        topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 250Mi

alertmanager:
  enabled: false

kubeStateMetrics:
  resources:
    limits:
      memory: 48Mi
    requests:
      memory: 16Mi