alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  retention: 1d
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 400Mi
